// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC586AyVjZHazFcgRurIFf89WHQAcUqAps',
    appId: '1:137722420255:web:a09a67a69f2a4f5290492a',
    messagingSenderId: '137722420255',
    projectId: 'todolist-ed311',
    authDomain: 'todolist-ed311.firebaseapp.com',
    storageBucket: 'todolist-ed311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZKS6aHOTK20BEqB_riCzr9Vn478wlyuE',
    appId: '1:137722420255:android:8902f1fd9537ae4890492a',
    messagingSenderId: '137722420255',
    projectId: 'todolist-ed311',
    storageBucket: 'todolist-ed311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalVg7_RDoTmXe4Vse7a5M3QBVPQC943c',
    appId: '1:137722420255:ios:cb38911dd04f7e8d90492a',
    messagingSenderId: '137722420255',
    projectId: 'todolist-ed311',
    storageBucket: 'todolist-ed311.appspot.com',
    androidClientId: '137722420255-6iu9okledn6l5avpr4juhaq416m84l2i.apps.googleusercontent.com',
    iosClientId: '137722420255-0pcj83lpah2tneoq4nbe1u8s0sfsa4ba.apps.googleusercontent.com',
    iosBundleId: 'hardik.todo.list.firebase.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalVg7_RDoTmXe4Vse7a5M3QBVPQC943c',
    appId: '1:137722420255:ios:186df647d3030d1490492a',
    messagingSenderId: '137722420255',
    projectId: 'todolist-ed311',
    storageBucket: 'todolist-ed311.appspot.com',
    androidClientId: '137722420255-6iu9okledn6l5avpr4juhaq416m84l2i.apps.googleusercontent.com',
    iosClientId: '137722420255-maqioquha6u8bne9n7djh6kulr2l2bno.apps.googleusercontent.com',
    iosBundleId: 'hardik.todo.list.firebase.flutterTodoFirebase.RunnerTests',
  );
}
