// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylsZ2Me_Qt6onhDfTrK3B9U1B6mWEweA',
    appId: '1:477138912947:web:0cee4de48012f5829cd2c6',
    messagingSenderId: '477138912947',
    projectId: 'random-chat-84e20',
    authDomain: 'random-chat-84e20.firebaseapp.com',
    storageBucket: 'random-chat-84e20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSVarks_9CS1xcgp8z8YTbwDO_DczL60',
    appId: '1:477138912947:android:1ef3a19d71508c659cd2c6',
    messagingSenderId: '477138912947',
    projectId: 'random-chat-84e20',
    storageBucket: 'random-chat-84e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1pQoK5RJA8QO9OJrUWCWUWLJg53-wEo',
    appId: '1:477138912947:ios:25722b141b4bb74d9cd2c6',
    messagingSenderId: '477138912947',
    projectId: 'random-chat-84e20',
    storageBucket: 'random-chat-84e20.appspot.com',
    iosBundleId: 'com.example.randomChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1pQoK5RJA8QO9OJrUWCWUWLJg53-wEo',
    appId: '1:477138912947:ios:319446a1b100433e9cd2c6',
    messagingSenderId: '477138912947',
    projectId: 'random-chat-84e20',
    storageBucket: 'random-chat-84e20.appspot.com',
    iosBundleId: 'com.example.randomChat.RunnerTests',
  );
}
